### ISSUE TITLE
Název

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFPIPE01#5]
Já bych to navrhoval přejmenovat na TFPIPE01. 
Vyšel bych tím vstříc tomu, aby tomu lidé říkali ThunderFly trubka.. 
Co si o tom myslíte @roman-dvorak  @ChroustJan ? 

Jinak ten repozitář vystřídal už několikátý název. Ještě před tím se jmenoval TFASPD01

**Comment by roman-dvorak** [comment]
Nemám s tím problém.
Chtěl jsem rozdělit ty jednotlivé konstrukce. Trubka, polička, ufo.
Klidně i zpět TFASPD01

**Comment by ChroustJan** [comment]
@kaklik  je tohle ještě aktuální?  Jinak za mě taky klidně.

**Comment by kaklik** [comment]
Přejmenováno.
